# Generated by Django 6.0.7 on 2026-08-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('REVIEW', 'Under Review'), ('REFINEMENT', 'Needs Refinement'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NEW', max_length=20),
        ),
    ]
